"""E3: zero-shot transfer of a frozen experience context to a different generator (plan v2 section 8).

Question Q5: does experience learned by model A, handed to model B verbatim, still help?

This is the decisive test of the project's central reframe. The H1/H2 asymmetry says the
useful object is not transcribed human chemistry (E0, distilled from 200 patent routes,
inconclusive) but a correction learned from the model's own failures (E*, reliable). If that
reading is right, E* encodes one model's failure modes and should transfer poorly. A null
result here therefore supports the reframe rather than refuting the project, and a positive
result means E* captured something more general than expected. Both outcomes are informative,
which is why this runs before anything is built on top of the idea.

Design (plan section 8.1): the frozen legacy E* -- not an E1 winner -- on the 40 predeclared
external_audit_panel targets, one route per condition, generated by the external model and
judged blind by the Gemini judge.

    uv run python scripts/run_e3_transfer.py --protocol-hash HASH --workers 8

Budget: 120 external generations and 80 judged pairs. The context is used verbatim and no
parameter is tuned for the new generator; only interface-required differences are allowed and
are recorded. Caveat carried into the report: the judge is the same family that trained E*,
so this is not a fully independent generate-evaluate combination.
"""

from __future__ import annotations

import argparse
import json
import logging
import sys
from concurrent.futures import ThreadPoolExecutor, as_completed
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))

from retro_e.api import OpenAICompatibleClient
from retro_e.config import ExperimentConfig, load_config
from retro_e.io import append_jsonl, assert_protocol, existing_keys, read_jsonl
from retro_e.judge import run_judging, source_winner
from retro_e.prompts import compose_generation_prompt, compose_generation_prompt_from_text
from retro_e.validation import validate_response

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
logger = logging.getLogger(__name__)

SAMPLES = 1
COMPARISONS = (("E_star", "baseline"), ("E_star", "E0"))

def conditions(config: ExperimentConfig) -> dict[str, str | None]:
    return {
        "baseline": None,
        "E0": config.paths.experience_e0.read_text(encoding="utf-8").strip(),
        "E_star": config.paths.experience_e_star.read_text(encoding="utf-8").strip(),
    }


def generate_one(
    config: ExperimentConfig,
    target: dict[str, Any],
    condition: str,
    text: str | None,
    sample_id: int,
    protocol_hash: str,
) -> dict[str, Any]:
    smiles = str(target["target_smiles"])
    prompt = (
        compose_generation_prompt(config, smiles, "baseline")
        if text is None
        else compose_generation_prompt_from_text(config, smiles, text)
    )
    with OpenAICompatibleClient(config) as client:
        completion = client.complete(
            prompt,
            temperature=config.generation.temperature,
            top_p=config.generation.top_p,
            max_tokens=config.generation.max_tokens,
            model=config.generator_model,
        )
    validation = validate_response(
        completion.content, smiles, expected_routes=config.generation.n_routes
    )
    return {
        "record_id": f"e3:{condition}:{target['target_id']}:{sample_id}:{protocol_hash[:12]}",
        "target_id": str(target["target_id"]),
        "target_smiles": smiles,
        "condition": condition,
        "sample_id": sample_id,
        "model": config.generator_model,
        "response_model": completion.response_model,
        "temperature": config.generation.temperature,
        "top_p": config.generation.top_p,
        "max_tokens": config.generation.max_tokens,
        "n_routes": config.generation.n_routes,
        "system_prompt_version": config.protocol.system_prompt_version,
        "experience_version": f"{condition}_legacy_frozen",
        "protocol_sha256": protocol_hash,
        "route_text": json.dumps(
            validation.normalized or validation.parsed, ensure_ascii=False,
            separators=(",", ":"),
        )
        if validation.parsed is not None
        else "",
        "raw_response": completion.content,
        "valid": validation.valid,
        "validation_errors": list(validation.errors),
        "validation_warnings": list(validation.warnings),
        "usage": completion.usage,
        "request_id": completion.request_id,
        "latency_seconds": completion.latency_seconds,
        "created_at": datetime.now(UTC).isoformat(),
    }


def generate_condition(
    config: ExperimentConfig,
    targets: list[dict[str, Any]],
    condition: str,
    text: str | None,
    output: Path,
    protocol_hash: str,
    workers: int,
) -> dict[str, int]:
    assert_protocol(output, protocol_hash)
    done = existing_keys(output, ["target_id", "sample_id"])
    jobs = [
        (target, sample_id)
        for target in targets
        for sample_id in range(SAMPLES)
        if (str(target["target_id"]), sample_id) not in done
    ]
    counts = {"planned": len(targets) * SAMPLES, "skipped": len(done), "completed": 0, "failed": 0}
    with ThreadPoolExecutor(max_workers=max(1, workers)) as pool:
        submitted = [
            pool.submit(generate_one, config, target, condition, text, sample_id, protocol_hash)
            for target, sample_id in jobs
        ]
        for future in as_completed(submitted):
            try:
                append_jsonl(output, future.result())
                counts["completed"] += 1
            except Exception:  # one dead request must not lose the others
                counts["failed"] += 1
                logger.exception("%s generation failed after retries", condition)
    return counts


def summarize(path: Path, favored: str) -> dict[str, Any]:
    rows = list(read_jsonl(path))
    by_pair: dict[str, list[dict[str, Any]]] = {}
    for row in rows:
        by_pair.setdefault(row["pair_id"], []).append(row)
    wins = losses = ties = 0
    for pair_rows in by_pair.values():
        winner = source_winner(pair_rows)
        if winner == favored:
            wins += 1
        elif winner == "Tie":
            ties += 1
        else:
            losses += 1
    total = len(by_pair)
    return {
        "pairs": total,
        "wins": wins,
        "losses": losses,
        "ties": ties,
        "net_win_rate": (wins - losses) / total if total else 0.0,
    }


def run(args: argparse.Namespace) -> None:
    # External model generates; the Gemini judge evaluates. Different families, but the judge
    # shares a family with the model E* was trained against: disclosed, not independent.
    config = load_config(args.config).with_roles(
        generator="external_generator", judge="judge"
    )
    targets = list(read_jsonl(Path("data/v2/external_audit_panel.jsonl")))
    out_dir = Path(config.paths.results_dir) / "transfer"
    gen_dir = out_dir / "generations"
    judge_dir = out_dir / "judgments"
    gen_dir.mkdir(parents=True, exist_ok=True)
    judge_dir.mkdir(parents=True, exist_ok=True)

    texts = conditions(config)
    logger.info(
        "E3 transfer: generator=%s judge=%s targets=%d conditions=%d",
        config.generator_model, config.judge_model, len(targets), len(texts),
    )

    if args.stage in ("all", "generate"):
        for condition, text in texts.items():
            counts = generate_condition(
                config, targets, condition, text,
                gen_dir / f"{condition}.jsonl", args.protocol_hash, args.workers,
            )
            logger.info("generated %s: %s", condition, counts)

    if args.stage in ("all", "judge"):
        for left, right in COMPARISONS:
            name = f"{left}_vs_{right}_transfer"
            run_judging(
                config,
                gen_dir / f"{left}.jsonl",
                gen_dir / f"{right}.jsonl",
                left, right, name,
                judge_dir / f"{name}.jsonl",
                args.protocol_hash,
                workers=args.workers,
            )
            logger.info("judged %s", name)

    if args.stage in ("all", "metrics"):
        report: dict[str, Any] = {
            "phase": "v2_pilot",
            "stage": "e3_zero_shot_transfer",
            "question": "Q5 -- does experience learned by one model transfer verbatim to another?",
            "protocol_sha256": args.protocol_hash,
            "transfer_generator": config.generator_model,
            "judge": config.judge_model,
            "context_source": "frozen legacy E* (round 1), used verbatim, nothing retuned",
            "targets": len(targets),
            "samples_per_target": SAMPLES,
            "votes_per_pair": config.judge.runs_per_pair,
            "validity_by_condition": {},
            "comparisons": {},
            "caveats": [
                (
                    "The external generator violates the step-ordering contract: step 1's "
                    "product must be the requested target and each later step's product must "
                    "have appeared as an earlier precursor, but it emits steps in forward "
                    "synthesis order. Measured 4/10 valid on panel targets. This is a "
                    "semantic contract failure, not a formatting one, and is NOT repaired: "
                    "invalid routes are retained and resolved by the predeclared validity "
                    "rule, identically for baseline, E0 and E_star."
                ),
                (
                    "The judge shares a model family with the generator E* was trained "
                    "against, so this is not a fully independent generate-evaluate pairing."
                ),
                (
                    "40 targets: a null result here does not rule out a small transfer "
                    "effect (plan section 8.2)."
                ),
                (
                    "If the external generator's baseline is weak or its invalid rate high, "
                    "the comparison says more about format handling than about transfer."
                ),
            ],
            "created_at": datetime.now(UTC).isoformat(),
        }
        for condition in texts:
            rows = list(read_jsonl(gen_dir / f"{condition}.jsonl"))
            invalid = sum(not row["valid"] for row in rows)
            report["validity_by_condition"][condition] = {
                "generations": len(rows),
                "invalid": invalid,
                "invalid_rate": invalid / len(rows) if rows else None,
            }
        for left, right in COMPARISONS:
            path = judge_dir / f"{left}_vs_{right}_transfer.jsonl"
            if path.exists():
                report["comparisons"][f"{left}_vs_{right}"] = summarize(path, left)
        summary = out_dir / "transfer_metrics.json"
        summary.write_text(
            json.dumps(report, ensure_ascii=False, indent=2, sort_keys=True) + "\n",
            encoding="utf-8",
        )
        print(json.dumps(
            {"validity": report["validity_by_condition"], "comparisons": report["comparisons"]},
            ensure_ascii=False, indent=2, sort_keys=True,
        ))
        logger.info("wrote %s", summary)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--protocol-hash", required=True)
    parser.add_argument("--config", default="config/v2_pilot.toml")
    parser.add_argument("--workers", type=int, default=8)
    parser.add_argument("--stage", choices=["all", "generate", "judge", "metrics"], default="all")
    run(parser.parse_args())


if __name__ == "__main__":
    main()
